### ISSUE TITLE
Tests fail on platforms with no SMP support

### ISSUE THREAD

**Issue by iliastsi** [haskell-crypto/cryptonite-conduit#3]
Hi!

Trying to build cryptonite-conduit for Debian does not work on architectures with no SMP support. It fails with the following error:

```
Running 1 test suites...
Test suite cryptonite-conduit-test: RUNNING...
cryptonite-conduit-test: unknown RTS option: -N
```

An example build is available at https://buildd.debian.org/status/fetch.php?pkg=haskell-cryptonite-conduit&arch=arm64&ver=0.2.0-1&stamp=1509402225&raw=0.

This is caused by `ghc-options:  -threaded -rtsopts -with-rtsopts=-N -W -Wall` in the cryptonite-conduit.cabal file.

Is there an absolute reason (besides performance) why cryptonite-conduit uses the `-N` RTS flag? Would it be possible to make this option dependent on the availability of SMP?

**Comment by snoyberg** [comment]
I think it should be OK in this case to remove the option. Any objection @vincenthz?

**Comment by vincenthz** [comment]
yes definitely
